/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "loueTonTelephone.h"

bool_t
xdr_livraison (XDR *xdrs, livraison *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->adresse, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->dateCommande, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_telephone (XDR *xdrs, telephone *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->appareil, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->prix))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_location (XDR *xdrs, location *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num))
		 return FALSE;
	 if (!xdr_telephone (xdrs, &objp->tel))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->date, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->enCours))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_client (XDR *xdrs, client *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->nom, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->adresse, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->tabLocation.tabLocation_val, (u_int *) &objp->tabLocation.tabLocation_len, ~0,
		sizeof (location), (xdrproc_t) xdr_location))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_assurance (XDR *xdrs, assurance *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->type, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->garantie, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->prix))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_enregistrerClientParam (XDR *xdrs, enregistrerClientParam *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->nom, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->adress, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_majInformationClientParam (XDR *xdrs, majInformationClientParam *objp)
{
	register int32_t *buf;

	 if (!xdr_client (xdrs, &objp->clt))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->nom, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->adresse, sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_effectuerLocationParam (XDR *xdrs, effectuerLocationParam *objp)
{
	register int32_t *buf;

	 if (!xdr_telephone (xdrs, &objp->tel))
		 return FALSE;
	 if (!xdr_client (xdrs, &objp->clt))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_annulerLocationParam (XDR *xdrs, annulerLocationParam *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->numLocation))
		 return FALSE;
	 if (!xdr_client (xdrs, &objp->clt))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_programmerLivraisonParam (XDR *xdrs, programmerLivraisonParam *objp)
{
	register int32_t *buf;

	 if (!xdr_client (xdrs, &objp->clt))
		 return FALSE;
	 if (!xdr_telephone (xdrs, &objp->tel))
		 return FALSE;
	return TRUE;
}
