/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "loueTonTelephone.h"


void louetontel_prog_1(char *host) {
	CLIENT *clnt;

#ifndef	DEBUG
	clnt = clnt_create (host, LOUETONTEL_PROG, LOUETONTEL_VERSION_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	/* Scénario 1 : Gérard (un nouveau client) */
	
	// Gérard allume sont application
	void * allumer_application_1_arg;
	void * result_1 = allumer_application_1((void*)&allumer_application_1_arg, clnt);
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "allumer_application_1 call failed\n");
	} else {
		printf("allumer_application_1 OK\n");
	}
	
	// Gérard s'enregistre en tant que nouveau client
	enregistrerClientParam enregistrer_client_1_arg;
	strcpy(enregistrer_client_1_arg.nom,"gerard");
	strcpy(enregistrer_client_1_arg.adresse,"5 bis rue george nikouni 29200 Brest");
	client * result_2 = enregistrer_client_1(&enregistrer_client_1_arg, clnt);
	if (result_2 != (client *) NULL) {
		clnt_perror (clnt, "enregistrer_client_1 call failed\n");
	} else {
		printf("enregistrer_client_1 OK\n");
	}
	
	// Gérard c'est trompé dans l'écriture de son adresse, il met à jour ses informations
	/*result_3 = maj_information_client_1(&maj_information_client_1_arg, clnt);
	if (result_3 == (client *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = effectuer_location_1(&effectuer_location_1_arg, clnt);
	if (result_4 == (location *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = annuler_location_1(&annuler_location_1_arg, clnt);
	if (result_5 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = afficher_nb_location_1(&afficher_nb_location_1_arg, clnt);
	if (result_6 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = afficher_location_1(&afficher_location_1_arg, clnt);
	if (result_7 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = modifier_location_1(&modifier_location_1_arg, clnt);
	if (result_8 == (location *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = effectuer_assurance_1(&effectuer_assurance_1_arg, clnt);
	if (result_9 == (assurance *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = afficher_type_assurance_1((void*)&afficher_type_assurance_1_arg, clnt);
	if (result_10 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = afficher_garantie_1(&afficher_garantie_1_arg, clnt);
	if (result_11 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = afficher_liste_telephone_1((void*)&afficher_liste_telephone_1_arg, clnt);
	if (result_12 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_13 = choisir_son_telephone_1(&choisir_son_telephone_1_arg, clnt);
	if (result_13 == (telephone *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_14 = afficher_information_telephone_1(&afficher_information_telephone_1_arg, clnt);
	if (result_14 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_15 = programmer_livraison_1(&programmer_livraison_1_arg, clnt);
	if (result_15 == (livraison *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_16 = annuler_livraison_1(&annuler_livraison_1_arg, clnt);
	if (result_16 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_17 = modifier_livraison_1(&modifier_livraison_1_arg, clnt);
	if (result_17 == (livraison *) NULL) {
		clnt_perror (clnt, "call failed");
	}*/
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[]) {
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	louetontel_prog_1 (host);
	exit (0);
}

