/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "loueTonTelephone.h"


void
louetontel_prog_1(char *host)
{
	CLIENT *clnt;
	client  *result_1;
	enregistrerClientParam  enregistrer_client_1_arg;
	client  *result_2;
	majInformationClientParam  maj_information_client_1_arg;
	location  *result_3;
	effectuerLocationParam  effectuer_location_1_arg;
	void  *result_4;
	annulerLocationParam  annuler_location_1_arg;
	char  *result_5;
	client  afficher_nb_location_1_arg;
	char  *result_6;
	client  afficher_location_1_arg;
	location  *result_7;
	telephone  modifier_location_1_arg;
	char  *result_8;
	char *afficher_type_assurance_1_arg;
	char  *result_9;
	assurance  afficher_garantie_1_arg;
	char  *result_10;
	char *afficher_liste_telephone_1_arg;
	livraison  *result_11;
	programmerLivraisonParam  programmer_livraison_1_arg;
	void  *result_12;
	livraison  annuler_livraison_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, LOUETONTEL_PROG, LOUETONTEL_VERSION_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = enregistrer_client_1(&enregistrer_client_1_arg, clnt);
	if (result_1 == (client *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = maj_information_client_1(&maj_information_client_1_arg, clnt);
	if (result_2 == (client *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = effectuer_location_1(&effectuer_location_1_arg, clnt);
	if (result_3 == (location *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = annuler_location_1(&annuler_location_1_arg, clnt);
	if (result_4 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = afficher_nb_location_1(&afficher_nb_location_1_arg, clnt);
	if (result_5 == (char *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = afficher_location_1(&afficher_location_1_arg, clnt);
	if (result_6 == (char *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = modifier_location_1(&modifier_location_1_arg, clnt);
	if (result_7 == (location *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = afficher_type_assurance_1((void*)&afficher_type_assurance_1_arg, clnt);
	if (result_8 == (char *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = afficher_garantie_1(&afficher_garantie_1_arg, clnt);
	if (result_9 == (char *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = afficher_liste_telephone_1((void*)&afficher_liste_telephone_1_arg, clnt);
	if (result_10 == (char *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = programmer_livraison_1(&programmer_livraison_1_arg, clnt);
	if (result_11 == (livraison *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = annuler_livraison_1(&annuler_livraison_1_arg, clnt);
	if (result_12 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	louetontel_prog_1 (host);
exit (0);
}
