/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h> 
#include <time.h> 
#include "loueTonTelephone.h"

#define NBCLIENTMAX 200

client listeClient[NBCLIENTMAX];
int nbClient;
telephone listeTelephone[3];

void * allumer_application_1_svc(void *argp, struct svc_req *rqstp) {
	nbClient = 0;
	
	information info1;
	strcpy(info1.processeur,"Helio P60");
	info1.ram = 3;
	info1.tailleEcran = 6.0;
	info1.autonomie = 12;
	info1.memoire = 128;
	info1.qualiteCamera = 8;
	strcpy(info1.systemeExploitation,"Android N");
	information info2;
	strcpy(info2.processeur,"Kirin 970");
	info2.ram = 4;
	info2.tailleEcran = 6.0;
	info2.autonomie = 12;
	info2.memoire = 128;
	info2.qualiteCamera = 10;
	strcpy(info2.systemeExploitation,"Android Oréo");
	information info3;
	strcpy(info3.processeur,"Snapdragon 845");
	info3.ram = 6;
	info3.tailleEcran = 6.4;
	info3.autonomie = 12;
	info3.memoire = 256;
	info3.qualiteCamera = 10;
	strcpy(info3.systemeExploitation,"Android Oréo");
	
	telephone tel1;
	strcpy(tel1.appareil,"Galaxy S20 FE");
	tel1.prix = 659.0;
	tel1.mesInformations = info1;
	telephone tel2;
	strcpy(tel2.appareil,"Galaxy S20");
	tel2.prix = 909.0;
	tel2.mesInformations = info2;
	telephone tel3;
	strcpy(tel3.appareil,"Galaxy S20+");
	tel3.prix = 1009.0;
	tel3.mesInformations = info3;
	listeTelephone[0] = tel1;
	listeTelephone[1] = tel2;
	listeTelephone[2] = tel3;
	printf("allumer_application - L'application est prête à être utilisé\n");
}

client * enregistrer_client_1_svc(enregistrerClientParam *argp, struct svc_req *rqstp) {
	enregistrerClientParam monClient = *argp;
	// Recherche du client
	for (int i = 0; i < nbClient; i++) {
		client clientActuel = listeClient[i];
		// Existe t-il ?
		if (strcmp(clientActuel.nom, monClient.nom) == 0) {
			// On retourne le client demandé
			printf("enregistrer_client - Le client nommé %s a été trouvé et retourné\n",monClient.nom);
			return &listeClient[i];
		}
	}
	// Création du nouveau client	
	static client result;

	strcpy(result.nom,argp->nom);
	strcpy(result.adresse,argp->adresse);
	result.nbLocation = 0;
	result.nbLivraison = 0;

	// Ajout du client sur le serveur
	listeClient[nbClient] = result;
	nbClient++;
	
	// On retourne le nouveau client
	printf("enregistrer_client - Le client nommé %s a été crée\n",result.nom);
	printf("%p\n", &result);
	return &result;
}

client * maj_information_client_1_svc(majInformationClientParam *argp, struct svc_req *rqstp) {
	static client result;
	majInformationClientParam data = *argp;
	char * ancienNom = data.ancienNom;
	// Recherche du client
	for (int i = 0; i < nbClient; i++) {
		client clientActuel = listeClient[i];
		// Existe t-il ?
		if (strcmp(clientActuel.nom, ancienNom) == 0) {
			// On met a jour ses informations
			strcpy(clientActuel.nom,data.nom);
			strcpy(clientActuel.adresse,data.nom);
			// On retourne le client modifié
			result = clientActuel;
		}
	}
	printf("maj_information_client - Vous avez modifié le client nommé %s\n",data.ancienNom);
	return &result;
}

location * effectuer_location_1_svc(effectuerLocationParam *argp, struct svc_req *rqstp) {
	effectuerLocationParam data = *argp;
	// Création de la nouvelle location
	static location result;
	result.num = data.nbLocation + 1;
	result.tel = data.tel;
	time_t t = time(NULL); // Recupère la date du jour
	// Transforme la date en une chaine de caractères
	strcpy(result.date,ctime(&t));
	result.enCours = 1;
	result.uneAssurance = data.uneAssurance;
	// On met à jour la table de location du client
	// Recherche du client
	for (int i = 0; i < nbClient; i++) {
		printf("aaa\n");
		client clientActuel = listeClient[i];
		// Existe t-il ?
		if (strcmp(clientActuel.nom, data.nom) == 0) {
			// On met a jour ses informations
			clientActuel.tabLocation[result.num] = result;
			clientActuel.nbLocation = result.num;
		}
	}
	assurance uneAssurance = data.uneAssurance;
	telephone tel = data.tel;
	printf("effectuer_location - Le client nommé %s a crée une nouvelle location pour le téléphone nommé %s. Celle-ci prend effet immédiatement. Le téléphone est assuré pendant %d mois\n",data.nom,tel.appareil,uneAssurance.duree);
	return &result;
}

void * annuler_location_1_svc(annulerLocationParam *argp, struct svc_req *rqstp) {
	annulerLocationParam data = *argp;
	// Recherche du client
	for (int i = 0; i < nbClient; i++) {
		client clientActuel = listeClient[i];
		// Existe t-il ?
		if (strcmp(clientActuel.nom, data.nom) == 0) {
			// On met a jour ses informations
			int j = data.numLocation;
			while (j < clientActuel.nbLocation) {
				clientActuel.tabLocation[j] = clientActuel.tabLocation[j+1];
				j++;
			}
			location loc;
			clientActuel.tabLocation[j] = loc;
			clientActuel.nbLocation--;
		}
	}
	printf("annuler_location - Le client nommé %s a annulé la location numéro %d\n",data.nom,data.numLocation);
}

void * afficher_nb_location_1_svc(client *argp, struct svc_req *rqstp) {
	client monClient = *argp;
	int nbLocationEnCours = 0;
	// Recherche du client
	for (int i = 0; i < nbClient; i++) {
		client clientActuel = listeClient[i];
		// Existe t-il ?
		if (strcmp(clientActuel.nom, monClient.nom) == 0) {
			for (int j = 0; j < monClient.nbLocation; j++) {
				location locationActuel = monClient.tabLocation[j];
				// La location est en cours ?
				if (locationActuel.enCours == 1) {
					// On incrémente le compteur
					nbLocationEnCours++;
				}
			}
		}
	}
	// Affichage du nombre de location en cours
	printf("afficher_nb_location - Le client nommé %s a %d location en cours\n",monClient.nom,nbLocationEnCours);
}

void * afficher_location_1_svc(client *argp, struct svc_req *rqstp) {
	client monClient = *argp;
	if (monClient.nbLocation == 0) {
		printf("afficher_location - Le client nommé %s n'a aucun location\n",monClient.nom);
	} else {
		if (monClient.nbLocation == 1) {
			printf("afficher_location - Le client nommé %s a la location suivante :\n",monClient.nom);
		} else {
			printf("afficher_location - Le client nommé %s a les locations suivantes :\n",monClient.nom);
		}
		// Recherche du client
		for (int i = 0; i < nbClient; i++) {
			client clientActuel = listeClient[i];
			// Existe t-il ?
			if (strcmp(clientActuel.nom, monClient.nom) == 0) {
				for (int j = 0; j < monClient.nbLocation; j++) {
					location locationActuel = monClient.tabLocation[j];
					telephone tel = locationActuel.tel;
					assurance monAssurance = locationActuel.uneAssurance;
					// Location en cours ?
					char * enCours = "Non";
					if (locationActuel.enCours == 1) {
						enCours = "Oui";
					}
					// Location avec assurance ?
					char * typeAssurance = "sans assurance";
					if (monAssurance.modePaiement == 1) {
						typeAssurance = "avec assurance (paiement en mensualité)";
					} else if (monAssurance.modePaiement == 2) {
						typeAssurance = "avec assurance (paiement unique)"; 
					}
					// Affichage des informations sur la location
					printf("Location numéro : %d - Téléphone : %s - Date de début : %s - En cours : %s - Type d'assurance : %s\n",locationActuel.num,tel.appareil,locationActuel.date,enCours,typeAssurance);
				}
			}
		}
	}
}

location * modifier_location_1_svc(modifierLocationParam *argp, struct svc_req *rqstp) {
	static location result;
	modifierLocationParam data = *argp;
	// Recherche du client
	for (int i = 0; i < nbClient; i++) {
		client clientActuel = listeClient[i];
		// Existe t-il ?
		if (strcmp(clientActuel.nom, data.nom) == 0) {
			// On crée une nouvelle location
			result.num = data.num;
			result.tel = data.tel;
			time_t t = time(NULL); // Recupère la date du jour
			// On l'attribut (en tant que char)
			strcpy(result.date,ctime(&t));
			result.enCours = 1;
			result.uneAssurance = data.uneAssurance;
			// On met a jour la location cible
			clientActuel.tabLocation[data.num] = result;
		}
	}
	assurance uneAssurance = data.uneAssurance;
	telephone tel = data.tel;
	printf("modifier_location - Le client nommé %s a modifié la location numéro %d, lui attribuant le téléphone nommé %s. Celle-ci prend effet immédiatement, et ce terminera dans %d\n",data.nom,data.num,tel.appareil,uneAssurance.duree);
	return &result;
}

assurance * effectuer_assurance_1_svc(int *argp, struct svc_req *rqstp) {
	int modePaiement = *argp;
	// Création de la nouvelle assurance
	static assurance  result;
	result.modePaiement = modePaiement;
	if (modePaiement == 1) {
		result.prix = 4.99;
		result.duree = 24;
		printf("effectuer_assurance - Une nouvelle assurance a été crée, payable en mensualité\n");
	} else if (modePaiement == 2) {
		result.prix = 89.00;
		result.duree = 24;
		printf("effectuer_assurance - Une nouvelle assurance a été crée, paiement unique\n");
	} else {
		result.prix = 0.0;
		result.duree = 0;
		printf("effectuer_assurance - Assurance non assurée\n");
	}
	return &result;
}

void * afficher_type_assurance_1_svc(void *argp, struct svc_req *rqstp) {
	printf("afficher_type_assurance - Il existe trois types d'assurances :\n - assurance avec paiement mensuel\n - assurance avec paiement unique\n - sans assurance\n");
}

void * afficher_garantie_1_svc(assurance *argp, struct svc_req *rqstp) {
	printf("afficher_garantie - Prendre une assurance vous octroie une protection contre tout vol ou dommage fait à votre appareil, à condition que celle-ci puissent être justifié. La garantie est valable pendant 24 mois.\n");
}

void * afficher_liste_telephone_1_svc(void *argp, struct svc_req *rqstp) {
	printf("afficher_liste_telephone - Les téléphones disponibles sont les suivants :\n");
	for (int i = 0; i < 3; i++) {
		telephone telActuel = listeTelephone[i];
		printf("mobile numéro %d - Nom : %s - Prix de l'appreil : %f\n",i,telActuel.appareil,telActuel.prix);
	}
}

telephone * choisir_son_telephone_1_svc(int *argp, struct svc_req *rqstp) {
	int num = *argp;
	static telephone result;
	telephone t = listeTelephone[num];
	strcpy(result.appareil,t.appareil);
	result.prix = t.prix;
	result.mesInformations = t.mesInformations;
	printf("choisir_son_telephone - Vous avez choisi le téléphone numéro %d, nommé %s\n",*argp,result.appareil);
	return &result;
}

void * afficher_information_telephone_1_svc(int *argp, struct svc_req *rqstp) {
	// On récupère le téléphone
	telephone tel = listeTelephone[*argp];
	information info = tel.mesInformations;
	printf("afficher_information_telephone - Téléphone numéro %d : Informations générale :\n",*argp);
	// on communique chaque informations du téléphone
	printf("Processeur : %s\n",info.processeur);
	printf("RAM : %d Go\n",info.ram);
	printf("Taille de l'écran : %f pouces\n",info.tailleEcran);
	printf("Autonomie estimé : %d heures\n",info.autonomie);
	printf("Mémoire interne : %d Go\n",info.memoire);
	printf("Résolution de la caméra : %d mégapixels\n",info.qualiteCamera);
	printf("Système d'exploitation : %s\n",info.systemeExploitation);
}

livraison * programmer_livraison_1_svc(programmerLivraisonParam *argp, struct svc_req *rqstp) {
	programmerLivraisonParam data = *argp;
	static livraison result;
	// Recherche du client
	for (int i = 0; i < nbClient; i++) {
		client clientActuel = listeClient[i];
		// Existe t-il ?
		if (strcmp(clientActuel.nom, data.nom) == 0) {
			// Création de la livraison
			strcpy(result.nom,data.nom);
			strcpy(result.adresse,data.adresse);
			result.tel = data.tel;
			result.enCours = 1;
			// On met a jour ses informations
			clientActuel.tabLivraison[data.nbLivraison+1] = result;
			clientActuel.nbLivraison = data.nbLivraison+1;
		}
	}
	
	telephone tel = data.tel;
	printf("programmer_livraison - La livraison à bien été crée. Le client nommé %s recevera sont téléphone %s sous 24h, à l'adresse %s\n Merci d'avoir commandé sur LoueTonTelephone !\n",data.nom,tel.appareil,data.adresse);
	return &result;
}

void * annuler_livraison_1_svc(annulerLivraisonParam *argp, struct svc_req *rqstp) {
	annulerLivraisonParam data = *argp;
	// Recherche du client
	for (int i = 0; i < nbClient; i++) {
		client clientActuel = listeClient[i];
		// Existe t-il ?
		if (strcmp(clientActuel.nom, data.nom) == 0) {
			// On met a jour ses informations
			int j = data.numLivraison;
			while (j < clientActuel.nbLivraison) {
				clientActuel.tabLivraison[j] = clientActuel.tabLivraison[j+1];
				j++;
			}
			livraison liv;
			clientActuel.tabLivraison[j] = liv;
			clientActuel.nbLivraison--;
		}
	}
	printf("annuler_livraison - Le client nommé %s a annulé la livraison numéro %d\n",data.nom,data.numLivraison);	
}

livraison * modifier_livraison_1_svc(modifierLivraisonParam *argp, struct svc_req *rqstp) {
	static livraison result;
	modifierLivraisonParam data = *argp;
	// Recherche du client
	for (int i = 0; i < nbClient; i++) {
		client clientActuel = listeClient[i];
		// Existe t-il ?
		if (strcmp(clientActuel.nom, data.nom) == 0) {
			// On crée une nouvelle livraison
			strcpy(result.nom,data.nom);
			strcpy(result.adresse,data.adresse);
			result.tel = data.tel;
			result.enCours = 1;
			// On met a jour la location cible
			clientActuel.tabLivraison[data.numLivraison] = result;
		}
	}
	telephone tel = data.tel;
	printf("modifier_livraison - Le client nommé %s a modifié la livraison numéro %d, lui attribuant le téléphone nommé %s. Le téléphone sera livré, sous un délais de 24h maximum, à l'adresse %s.\n",data.nom,data.numLivraison,tel.appareil,data.adresse);
	return &result;
}
