/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "loueTonTelephone.h"


void louetontel_prog_1(char *host) {
	CLIENT *clnt;

#ifndef	DEBUG
	clnt = clnt_create (host, LOUETONTEL_PROG, LOUETONTEL_VERSION_1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	/* Scénario 1 : Gérard (un nouveau client) */
	
	printf("\nGérard allume son application\n");
	// PARAM
	void * allumer_application_1_arg;
	// EXECUTION
	void * result_1 = allumer_application_1((void*)&allumer_application_1_arg, clnt);
	// TRAITEMENT
	if (result_1 == (void *) NULL) {
		clnt_perror (clnt, "allumer_application_1 call failed\n");
	} else {
		printf("allumer_application_1 OK\n");
	}
	
	printf("\nGérard s'enregistre en tant que nouveau client\n");
	// PARAM
	enregistrerClientParam enregistrer_client_1_arg;
	strcpy(enregistrer_client_1_arg.nom,"gerard");
	strcpy(enregistrer_client_1_arg.adresse,"5 bis rue george nikouni 29200 Brest");
	// EXECUTION
	client * result_2 = enregistrer_client_1(&enregistrer_client_1_arg, clnt);
	/*printf("%p\n",result_2);
	
	printf("%p\n",enregistrer_client_1(&enregistrer_client_1_arg, clnt));
	printf("%s\n",result_2->nom);*/
	// TRAITEMENT
	if (result_2 == (client *) NULL) {
		clnt_perror (clnt, "enregistrer_client_1 call failed\n");
	} else {
		printf("enregistrer_client_1 OK\n");
	}
	
	printf("\nGérard s'est trompé dans l'écriture de son adresse, il met à jour ses informations\n");
	// PARAM
	majInformationClientParam maj_information_client_1_arg;
	strcpy(maj_information_client_1_arg.ancienNom,"gerard");
	strcpy(maj_information_client_1_arg.nom,"gerard");
	strcpy(maj_information_client_1_arg.adresse,"10 bis rue george nikouni 29200 Brest");
	// EXECUTION
	client * result_3 = maj_information_client_1(&maj_information_client_1_arg, clnt);
	printf("%s\n", result_3->nom);
	// TRAITEMENT
	if (result_3 == (client *) NULL) {
		clnt_perror (clnt, "maj_information_client_1 call failed\n");
	} else {
		printf("maj_information_client_1 OK\n");
	}
	
	printf("\nGérard souhaite un téléphone. Il veux avoir la liste de ceux disponibles\n");
	// PARAM
	void * afficher_liste_telephone_1_arg;
	// EXECUTION
	void * result_4 = afficher_liste_telephone_1((void*)&afficher_liste_telephone_1_arg, clnt);
	// TRAITEMENT
	if (result_4 == (void *) NULL) {
		clnt_perror (clnt, "afficher_liste_telephone_1 call failed\n");
	} else {
		printf("afficher_liste_telephone_1 OK\n");
	}
	
	printf("\nGérard hésite à prendre le téléphone Galaxy S20. Il demande d'avantage d'informations sur ce téléphone\n");
	// PARAM
	int afficher_information_telephone_1_arg = 1;
	// EXECUTION
	void * result_5 = afficher_information_telephone_1((void*)&afficher_information_telephone_1_arg, clnt);
	// TRAITEMENT
	if (result_5 == (void *) NULL) {
		clnt_perror (clnt, "afficher_information_telephone_1 call failed\n");
	} else {
		printf("afficher_information_telephone_1 OK\n");
	}
	
	printf("\nGérard est intéressé par le téléphone Galaxy S20. Il choisit donc ce téléphone\n");
	// PARAM
	int choisir_son_telephone_1_arg = 1;
	// EXECUTION
	telephone * result_6 = choisir_son_telephone_1((void*)&choisir_son_telephone_1_arg, clnt);
	// TRAITEMENT
	if (result_6 == (telephone *) NULL) {
		clnt_perror (clnt, "choisir_son_telephone_1 call failed\n");
	} else {
		printf("choisir_son_telephone_1 OK\n");
	}
	
	printf("\nGérard souhaite connaître les assurances disponibles\n");
	// PARAM
	void * afficher_type_assurance_1_arg;
	// EXECUTION
	void * result_7 = afficher_type_assurance_1((void*)&afficher_type_assurance_1_arg, clnt);
	// TRAITEMENT
	if (result_7 == (void *) NULL) {
		clnt_perror (clnt, "afficher_type_assurance_1 call failed\n");
	} else {
		printf("afficher_type_assurance_1 OK\n");
	}
	
	printf("\nGérard souhaite connaître les détails de la garantie\n");
	// PARAM
	void * afficher_garantie_1_arg;
	// EXECUTION
	void * result_8 = afficher_garantie_1((void*)&afficher_garantie_1_arg, clnt);
	// TRAITEMENT
	if (result_8 == (void *) NULL) {
		clnt_perror (clnt, "afficher_garantie_1 call failed\n");
	} else {
		printf("afficher_garantie_1 OK\n");
	}
	
	printf("\nGérard souhaite prendre une assurance payable en mensualité\n");
	// PARAM
	int effectuer_assurance_1_arg = 1;
	// EXECUTION
	assurance * result_9 = effectuer_assurance_1((void*)&effectuer_assurance_1_arg, clnt);
	// TRAITEMENT
	if (result_9 == (assurance *) NULL) {
		clnt_perror (clnt, "effectuer_assurance_1 call failed\n");
	} else {
		printf("effectuer_assurance_1 OK\n");
	}
	
	printf("\nGérard souhaite faire une location du téléphone Galaxy S20 avec assurance payable en mensualité\n");
	// PARAM
	effectuerLocationParam * effectuer_location_1_arg;
	effectuer_location_1_arg = (effectuerLocationParam *) malloc(sizeof(effectuerLocationParam));
	printf("aaa\n");
	effectuer_location_1_arg->tel = *result_6;
	printf("bbb\n");
	strcpy(effectuer_location_1_arg->nom,"gerard");
	printf("ccc\n");
	client * gerard;
	gerard = (client *) malloc(sizeof(client));
	gerard = result_3;
	printf("ddd\n");
	effectuer_location_1_arg->nbLocation = gerard->nbLocation;
	printf("eee\n");
	effectuer_location_1_arg->uneAssurance = *result_9;
	printf("fff\n");
	// EXECUTION
	printf("ggg\n");
	location * result_10 = effectuer_location_1((void*) effectuer_location_1_arg, clnt);
	printf("hhh\n");
	// TRAITEMENT
	if (result_10 == (location *) NULL) {
		clnt_perror (clnt, "effectuer_location_1 call failed\n");
	} else {
		printf("effectuer_location_1 OK\n");
	}
	
	printf("\nAprès des recherches personnelles, Gérard se rend compte que le téléphone Galaxy S20+ lui correspondrait mieux. Il veut annuler sa précédente location\n");
	// PARAM
	annulerLocationParam annuler_location_1_arg;
	annuler_location_1_arg.numLocation = 1;
	strcpy(annuler_location_1_arg.nom,"gerard");
	// EXECUTION
	void * result_11 = annuler_location_1((void*)&annuler_location_1_arg, clnt);
	// TRAITEMENT
	if (result_11 == (void *) NULL) {
		clnt_perror (clnt, "annuler_location_1 call failed\n");
	} else {
		printf("annuler_location_1 OK\n");
	}
	
	/*printf("\nGérard souhaite faire une location du téléphone Galaxy S20+ avec assurance payable en mensualité\n");
	// PARAM
	effectuerLocationParam effectuer_location_1_arg2;
	// EXECUTION
	location * result_12 = effectuer_location_1((void*)&effectuer_location_1_arg2, clnt);
	// TRAITEMENT
	if (result_12 != (void *) NULL) {
		clnt_perror (clnt, "effectuer_location_1 call failed\n");
	} else {
		printf("effectuer_location_1 OK\n");
	}
	
	printf("\nGérard souhaite savoir combien il a de locations en cours\n");
	
	printf("\nGérard souhaite afficher ses locations\n");
	// PARAM
	client afficher_location_1_arg = result_3;
	// EXECUTION
	void * result_13 = afficher_location_1((void*)&afficher_location_1_arg, clnt);
	// TRAITEMENT
	if (result_13 != (void *) NULL) {
		clnt_perror (clnt, "afficher_location_1 call failed\n");
	} else {
		printf("afficher_location_1 OK\n");
	}*/
	
	/*result_4 = effectuer_location_1(&effectuer_location_1_arg, clnt);
	if (result_4 == (location *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = annuler_location_1(&annuler_location_1_arg, clnt);
	if (result_5 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = afficher_nb_location_1(&afficher_nb_location_1_arg, clnt);
	if (result_6 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = afficher_location_1(&afficher_location_1_arg, clnt);
	if (result_7 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = modifier_location_1(&modifier_location_1_arg, clnt);
	if (result_8 == (location *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_9 = effectuer_assurance_1(&effectuer_assurance_1_arg, clnt);
	if (result_9 == (assurance *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_10 = afficher_type_assurance_1((void*)&afficher_type_assurance_1_arg, clnt);
	if (result_10 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_11 = afficher_garantie_1(&afficher_garantie_1_arg, clnt);
	if (result_11 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_12 = afficher_liste_telephone_1((void*)&afficher_liste_telephone_1_arg, clnt);
	if (result_12 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_13 = choisir_son_telephone_1(&choisir_son_telephone_1_arg, clnt);
	if (result_13 == (telephone *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_14 = afficher_information_telephone_1(&afficher_information_telephone_1_arg, clnt);
	if (result_14 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_15 = programmer_livraison_1(&programmer_livraison_1_arg, clnt);
	if (result_15 == (livraison *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_16 = annuler_livraison_1(&annuler_livraison_1_arg, clnt);
	if (result_16 == (void *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_17 = modifier_livraison_1(&modifier_livraison_1_arg, clnt);
	if (result_17 == (livraison *) NULL) {
		clnt_perror (clnt, "call failed");
	}*/
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[]) {
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	louetontel_prog_1 (host);
	exit (0);
}
